### PR TITLE
Place IE8 reserved word(default) in brackets.

### PR DESCRIPTION
**Pull request by impatient**
Failing when un-minified in IE8.

### CODE REVIEW

**Comment by christopherthielen** [comment]
Besides this stuff, does ui router and ui router extras work ok in ie8 these days?

**Comment by impatient** [comment]
Seems to.  We're only using sticky states and not too heavily at this point. 

Thanks!

**Comment by christopherthielen** [comment]
Cool.  Can you squash this down to a single commit with a commit message "fix(extras): restore ie8 compatibility due to reserved words"

**Comment by christopherthielen** [comment]
oh, and remove the built file (release/ct-ui-router-extras.js)

**Comment by gabrielmaldi** [comment]
I was just about to same this exact PR :smile: 

It's not just IE 8, some Android 2.x Stock Browsers (not all, depending on the vendor), and thus Web Views too, fail to take the context into account when interpreting reserved keywords and break.

**Comment by mdreizin** [comment]
@christopherthielen could you please merge and release this fix?

**Pull request merged**
