### PR TITLE
Export the module names for various modules

### LINKED ISSUE #326: Export the module name
When using angular-poller with CommonJS `require` statements it's not possible to retrieve the AngularJS module name from the module. 

Most AngularJS modules published to npm export the module name string value so they can be used like following [example](https://www.npmjs.com/package/angular-resource): 

```js
angular.module('myApp', [require('angular-resource')]);
```

### PR DESCRIPTION
**Pull request by mgol**
Fix #326

### CODE REVIEW

**Comment by mgol** [comment]
The whole module import examples:

CommonJS:
```js
const uiRouterExtras = require('ui-router-extras');
angular.module('myModule', [uiRouterExtras]);
```

ES6 (when used with Webpack etc.):
```js
import uiRouterExtras from 'ui-router-extras';
angular.module('myModule', [uiRouterExtras]);
```

I've also added exports for separate nodules, example:
```js
import uiRouterExtrasTransition from 'ui-router-extras/modules/transition';
angular.module('myModule', [v]);
```

**Comment by mgol** [comment]
Remaining issues:

1. It'd be good to test it somehow.
2. Currently the dependencies lists are duplicated, they need to be provided both in the original files as module names and in the `./modules/*.js` files in the form of `require`-ing everything that's required (no pun intended).

WDYT?

**Comment by christopherthielen** [comment]
Thanks for the PR!  

I think these exports belong in the individual source files like `src/dsr.js`. Then, the angular module name will also be included into the bundled files too (which go onto the CDNs, etc)

Here's what I'm talking about: https://github.com/christopherthielen/ui-router-extras/compare/export_module_names?expand=1


The downside is that without the commonjs `modules/*` from your PR, we don't get the automatic`require()`ing of the dependent modules like ui-router-core.  I'd love to convert to a commonjs + webpack build, but at this point in ui-router-extras lifespan I'm wary of changing things up much.

**Comment by mgol** [comment]
We could check if we're in a CommonJS environment and require dependencies then. Something like: https://github.com/krispo/angular-nvd3/blob/v1.0.9/src/angular-nvd3.js#L7-L11

**Comment by mgol** [comment]
@christopherthielen What do you think about my proposal?

**Comment by christopherthielen** [comment]
@mgol that sounds like a reasonable approach.  Want to update your PR?

**Comment by mgol** [comment]
Sure! Just not today. :)

**Comment by mgol** [comment]
I assume this PR is no longer needed since the whole repository is EOL'd.

**Pull request closed without merging**
