### PR TITLE
chore(gulp): adds UMD to support browserify/webpack

### PR DESCRIPTION
**Pull request by mdreizin**
Currently it is not possible to use in node env., but it helps to fix that.

### CODE REVIEW

**Comment by mdreizin** [comment]
@christopherthielen Could you please review it and provide feedback if it has some issues. If you have some questions I would be more than happy to answer on them.

It is very important for me and I guess for some guys whom use browserify/webpack.

I ran tests and it worked fine without any issues and also I can tell you that is worked perfect on webpack.

**Comment by ZIJ** [comment]
@christopherthielen This would fix my issues as well. Could you please review that?

**Comment by vladferix** [comment]
+1
It would be nice to have this feature in my project too.

**Comment by christopherthielen** [comment]
I want to make sure I don't make a short-sighted decision on this.  I don't know enough about JS modules at this point to make an informed decision.  I only have some limited experience using AMD.  Help me understand the ramifications.

- Eventually I want to distribute this project as an ES6 module.  How will wrapping as UMD now affect my ability to publish as ES6 later?

- I already am splitting my codebase up into smaller angular modules, and publishing both the individual module JS files, as well as the fullly concatenated project.  However, I am not exporting my own modules as real JS modules, and I'm forcing my users to manage script tags manually.  
  - I don't know how I should best go about packaging or publishing my modular project, but I'm not sure that wrapping each of my modules in UMD is the correct approach.  
  - If I did wrap each module as UMD, how should I declare my module's own internal dependencies for all the module loaders that UMD supports?

**Comment by nateabele** [comment]
> Eventually I want to distribute this project as an ES6 module. How will wrapping as UMD now affect my ability to publish as ES6 later?

This involves some amount of BC-break either way (albeit mostly search-&-replaceable), but otherwise UMD vs. not-UMD is kind of a non-factor.

**Comment by christopherthielen** [comment]
@nateabele  so you don't think I'd be shooting myself (or my users) in the foot by publishing the full JS as UMD?

**Comment by nateabele** [comment]
I can't say whether that would be the case _now_, I'm just saying that, when you go ES6, you can transpile to AMD, UMD, CJS, SystemJS, or whatever gets invented tomorrow.

**Comment by christopherthielen** [comment]
manually merged umd wrapper (for monolithic build only)

**Pull request closed without merging**
