### PR TITLE
feat($previousState): allow to memo a state passed by parameter.

### PR DESCRIPTION
**Pull request by gabrielmaldi**
Add a `set` method to `$previousState` to programmatically set the previous state.

### CODE REVIEW

**Comment by christopherthielen** [comment]
So you want to programmatically set the previous state?

What if we added `.set(memoName, previousState, previousParams)` instead?

**Comment by gabrielmaldi** [comment]
Your approach is far better the overloading the meaning of `memo` and `defaultStateName`. Updated the PR!

**Comment by christopherthielen** [comment]
Thanks! Would you mind adding `.set` to the docs?

here: https://github.com/christopherthielen/ui-router-extras/blob/gh-pages/partials/previous/api.html#L6-L22

**Comment by gabrielmaldi** [comment]
Done in #303

**Pull request merged**
